# -*- coding: utf-8 -*-
"""Colab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o-A641pH8vID1CKDhqo8ukZ_fbvrVABZ

# Colab 사용설명서
"""

# 플랫폼 정보를 보는것. 어떤 운영체제의 이미지이냐
import platform
platform.platform()

# !가 들어가면 리눅스 명령어임
# cat은 모니터링 본다 라는 의미
# ect폴더안에 issue.net에 정보가 들어있다 -> 운영체제 정보임
!cat /etc/issue.net

# cpu정보
!cat /proc/cpuinfo

# 메모리크기
!cat /proc/meminfo

# 하드디스크의 정보
!df -h

# 파이썬 버전 확인
!python --version

# 그래픽카드 정보 확인
!nvidia-smi

# 명령어 검색
help()

a = ['one', 'two', '3']
a

a.clear()
a

# ? help와 비슷한 기능으로 기능에 대한 사용법이 나온다
?len()

"""매직 명령어

- % : 한 줄의 코드만 실행
- %% : 여러줄의 코드를 실행
"""

# Commented out IPython magic to ensure Python compatibility.
# # 파일을 만드는 방법
# %%writefile a.py
# print("Hello")

# 리눅스 명령어로 리스트를 보여줌
!ls

# 리북스 명령어 현재 내 위치를 알려주는
!pwd

"""# 마크다운

# 큰 제목 (#)
## 작은 제목(##)
### 더 작은 제목 (###)
###### 제일 작은 제목(#*6)

목록


1.   항목 추가
2.   항목 추가



*   항목 추가
*   항목 추가
  - 단계
      - 단계
"""